# Generated by Django 5.1.6 on 2025-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='route_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='distance'),
        ),
        migrations.AddField(
            model_name='routes',
            name='route_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='duration'),
        ),
    ]
