# Generated by Django 5.1.6 on 2025-03-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_routes_route_distance_routes_route_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='routefares',
            name='student_fare',
            field=models.FloatField(blank=True, null=True, verbose_name='student_fare'),
        ),
        migrations.AddField(
            model_name='routes',
            name='route_url',
            field=models.CharField(default='/deneme', max_length=255, unique=True, verbose_name='route_url'),
            preserve_default=False,
        ),
    ]
