# Generated by Django 5.1.6 on 2025-03-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_routefares_student_fare_routes_route_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeschedules',
            name='end_time',
        ),
    ]
